### PR TITLE
added link to bsonpatch, a port of zjsonpatch that uses BSON as document model

### PR DESCRIPTION
**Pull request by dandoug**

### CODE REVIEW

**Comment by almost** [comment]
Is this still JSONPatch if it's using BSON?

**Comment by dandoug** [comment]
It’s still RFC 6902. Just with a binary document encoding instead of a textual one.

To the extent that “JSONPatch” is synonymous with RFC 6902, the answer to your question is “yes”.

Someone working in BSON that wants to do diffs between documents will find jsonpatch.com and a link there to bsonpatch would be really useful to them.


Dan
________________________________

**Comment by almost** [comment]
Seems reasonable, I'll add it in. If we get many more using non JSON formats we might need to restructure the site a little to separate them I guess

**Comment by almost** [comment]
Have merged, thanks Dan!

**Comment by dandoug** [comment]
thank you!

**Pull request merged**
